services:
  communityecommercespaliberia:
    image: communityecommercespaliberia
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
