[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --only=production"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
